language: php
sudo: false

matrix:
  include:
    - php: 7.1
      env: TYPO3=^8.0
    - php: 7.1
      env: TYPO3=^7.6.0
    - php: 7.0
      env: TYPO3=^8.0
    - php: 7.0
      env: TYPO3=^7.6.0
    - php: 5.6
      env: TYPO3=^7.6.0
    - php: 5.5
      env: TYPO3=^6.2.0

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache


before_install:
#  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

before_script:
  - composer require typo3/cms="$TYPO3"
  # Restore composer.json
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/Web

script:
   - >
     echo;
     echo "Running unit tests";
     ls -l;
     Resources/Libraries/bin/phpunit -c Resources/Libraries/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
