language: php
sudo: false

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5

env:
  - TYPO3_VERSION=^8.6
  - TYPO3_VERSION=^7.6
  - TYPO3_VERSION=^6.2

before_script:
  - export TYPO3_PATH_WEB=$PWD
  - composer require typo3/cms="$TYPO3_VERSION"

script:
  - Resources/Libraries/bin/phpunit -c Resources/Libraries/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

matrix:
  exclude:
    - php: 7.1
      env: TYPO3_VERSION=^6.2
    - php: 7.0
      env: TYPO3_VERSION=^6.2
    - php: 5.6
      env: TYPO3_VERSION=^8.6
    - php: 5.5
      env: TYPO3_VERSION=^8.6
